// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewFilms.Api.Data;

#nullable disable

namespace ReviewFilms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407022055_Initial_Create_Pomelo")]
    partial class Initial_Create_Pomelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ReviewFilms.Api.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Depth")
                        .HasColumnType("int")
                        .HasColumnName("depth");

                    b.Property<int>("DownvoteCount")
                        .HasColumnType("int")
                        .HasColumnName("downvote_count");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edited_at");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_edited");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_id");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("int")
                        .HasColumnName("reply_count");

                    b.Property<Guid?>("RootId")
                        .HasColumnType("char(36)")
                        .HasColumnName("root_id");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int")
                        .HasColumnName("upvote_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_comment_movie_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_comment_parent_id");

                    b.HasIndex("RootId")
                        .HasDatabaseName("ix_comment_root_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_user_id");

                    b.HasIndex("MovieId", "RootId", "CreatedAt")
                        .HasDatabaseName("ix_comment_movie_id_root_id_created_at");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.CommentVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vote_type");

                    b.HasKey("Id")
                        .HasName("pk_comment_vote");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_vote_comment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_vote_user_id");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_comment_vote_comment_id_user_id");

                    b.ToTable("comment_vote", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_slug");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AgeRating")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("age_rating");

                    b.Property<decimal?>("AvgRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("avg_rating");

                    b.Property<string>("BackdropUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("backdrop_url");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int")
                        .HasColumnName("comment_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("original_language");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasColumnType("longtext")
                        .HasColumnName("overview");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("poster_url");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int")
                        .HasColumnName("rating_count");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("int")
                        .HasColumnName("runtime_minutes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("trailer_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_movie");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_movie_created_by_user_id");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_movie_release_date");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_movie_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_movie_status");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_movie_title");

                    b.ToTable("movie", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.MovieCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int?>("BillingOrder")
                        .HasColumnType("int")
                        .HasColumnName("billing_order");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("character_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreditType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credit_type");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Job")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("job");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_moviecredits");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_moviecredits_movie_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_moviecredits_person_id");

                    b.HasIndex("MovieId", "PersonId", "CreditType", "Job", "CharacterName")
                        .HasDatabaseName("ix_moviecredits_movie_id_person_id_credit_type_job_character_na");

                    b.ToTable("moviecredits", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("char(36)")
                        .HasColumnName("genre_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("MovieId", "GenreId")
                        .HasName("pk_movie_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_movie_genres_genre_id");

                    b.ToTable("movie_genres", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.MovieRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_id");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score")
                        .HasComment("Suggested range: 1..10");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_movie_rating");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_movie_rating_movie_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_movie_rating_user_id");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasDatabaseName("ix_movie_rating_user_id_movie_id");

                    b.ToTable("movie_rating", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .HasColumnType("json")
                        .HasColumnName("data_json");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_user_id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_notification_user_id_is_read_created_at");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_code");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Biography")
                        .HasColumnType("longtext")
                        .HasColumnName("biography");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Deathday")
                        .HasColumnType("date")
                        .HasColumnName("deathday");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<string>("KnownForDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("known_for_department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_name");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_persons_name");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_name");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("JwtId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("jwt_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("char(36)")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("JwtId")
                        .HasDatabaseName("ix_refresh_token_jwt_id");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_token_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("longtext")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("target_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_report");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_report_reporter_user_id");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_report_reviewed_by_user_id");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_report_target_type_target_id");

                    b.HasIndex("TargetType", "TargetId", "Status")
                        .HasDatabaseName("ix_report_target_type_target_id_status");

                    b.ToTable("report", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_code");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permission");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_role_permission_created_by_user_id");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permission_permission_id");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assigned_by");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_user_role_assigned_by_user_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("added_at");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_id");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("watched_at");

                    b.HasKey("Id")
                        .HasName("pk_watchlist");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_watchlist_movie_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_watchlist_user_id");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasDatabaseName("ix_watchlist_user_id_movie_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_watchlist_user_id_status");

                    b.ToTable("watchlist", (string)null);
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Comment", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comment_movie_movie_id");

                    b.HasOne("ReviewFilms.Api.Entities.Comment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_comment_comment_parent_id");

                    b.HasOne("ReviewFilms.Api.Entities.Comment", "RootComment")
                        .WithMany("ThreadComments")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_comment_comment_root_id");

                    b.HasOne("ReviewFilms.Api.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comment_user_user_id");

                    b.Navigation("Movie");

                    b.Navigation("ParentComment");

                    b.Navigation("RootComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.CommentVote", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.Comment", "Comment")
                        .WithMany("CommentVotes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comment_vote_comment_comment_id");

                    b.HasOne("ReviewFilms.Api.Entities.User", "User")
                        .WithMany("CommentVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comment_vote_user_user_id");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Movie", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.User", "CreatedByUser")
                        .WithMany("CreatedMovies")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_movie_user_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.MovieCredit", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.Movie", "Movie")
                        .WithMany("MovieCredits")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_moviecredits_movie_movie_id");

                    b.HasOne("ReviewFilms.Api.Entities.Person", "Person")
                        .WithMany("MovieCredits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_moviecredits_persons_person_id");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.MovieGenre", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_genres_genre_id");

                    b.HasOne("ReviewFilms.Api.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_movies_movie_id");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.MovieRating", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.Movie", "Movie")
                        .WithMany("MovieRatings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_movie_rating_movie_movie_id");

                    b.HasOne("ReviewFilms.Api.Entities.User", "User")
                        .WithMany("MovieRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_movie_rating_user_user_id");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Notification", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany("ReplacedTokens")
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_refresh_token_refresh_token_replaced_by_token_id");

                    b.HasOne("ReviewFilms.Api.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_user_id");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Report", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.User", "ReporterUser")
                        .WithMany("ReportsFiled")
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_report_user_reporter_user_id");

                    b.HasOne("ReviewFilms.Api.Entities.User", "ReviewedByUser")
                        .WithMany("ReportsReviewed")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_report_user_reviewed_by_user_id");

                    b.Navigation("ReporterUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.RolePermission", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.User", "CreatedByUser")
                        .WithMany("CreatedRolePermissions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_role_permission_user_created_by_user_id");

                    b.HasOne("ReviewFilms.Api.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_permission_permission_id");

                    b.HasOne("ReviewFilms.Api.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.UserRole", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.User", "AssignedByUser")
                        .WithMany("AssignedUserRoles")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_user_role_user_assigned_by_user_id");

                    b.HasOne("ReviewFilms.Api.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("ReviewFilms.Api.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Watchlist", b =>
                {
                    b.HasOne("ReviewFilms.Api.Entities.Movie", "Movie")
                        .WithMany("Watchlists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_movie_movie_id");

                    b.HasOne("ReviewFilms.Api.Entities.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_user_user_id");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Comment", b =>
                {
                    b.Navigation("ChildComments");

                    b.Navigation("CommentVotes");

                    b.Navigation("ThreadComments");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Movie", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("MovieCredits");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieRatings");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Person", b =>
                {
                    b.Navigation("MovieCredits");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.RefreshToken", b =>
                {
                    b.Navigation("ReplacedTokens");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ReviewFilms.Api.Entities.User", b =>
                {
                    b.Navigation("AssignedUserRoles");

                    b.Navigation("CommentVotes");

                    b.Navigation("Comments");

                    b.Navigation("CreatedMovies");

                    b.Navigation("CreatedRolePermissions");

                    b.Navigation("MovieRatings");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReportsFiled");

                    b.Navigation("ReportsReviewed");

                    b.Navigation("UserRoles");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
